package com.attilapalfi

/**
 * Created by 212461305 on 2016.03.16..
 */
val DEFAULT_WINDOW_WIDTH = 1280
val DEFAULT_WINDOW_HEIGHT = 720

@Volatile
var CURRENT_WINDOW_WIDTH: Int = DEFAULT_WINDOW_WIDTH
@Volatile
var CURRENT_WINDOW_HEIGHT: Int = DEFAULT_WINDOW_HEIGHT

val WORLD_HEIGHT: Float = 18f
val WORLD_WIDTH: Float = (WORLD_HEIGHT * CURRENT_WINDOW_WIDTH) / CURRENT_WINDOW_HEIGHT