package com.attilapalfi

/**
 * Created by 212461305 on 2016.03.16..
 */
var CURRENT_WINDOW_WIDTH = DEFAULT_WINDOW_WIDTH
var CURRENT_WINDOW_HEIGHT = DEFAULT_WINDOW_HEIGHT

val WORLD_HEIGHT: Float = 18f
var WORLD_WIDTH: Float = (WORLD_HEIGHT * CURRENT_WINDOW_WIDTH) / CURRENT_WINDOW_HEIGHT